development:
  host: http://eryc-taylor-dance.herokuapp.com/
  email: eric.yuhui.liu@gmail.com
  password: 753951
  api_key: be7648fb7c1227103fa036dc90d0f85a2a30603d
staging:
  host: staging.example.com
  email: john@doe.net
  password: apassword
  # api_key: <your api key here>
production:
  host: www.example.com
  email: john@doe.net
  password: apassword
  # api_key: <your api key here>